<?php
/**
 * SPDX-FileCopyrightText: 2026 Eric van der Vlist <vdv@dyomedea.com>
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * Stand-in for the part of wpdb used by the plugin.
 *
 * @package Otherguise
 */

/**
 * The subset of wpdb the plugin uses, with the same behavior for `prepare()`, built on mysqli.
 *
 * Without a connection it only records the queries, which is enough for the tests that do not need a database. With a connection it
 * runs them on a real MySQL or MariaDB, so that the SQL, the indexes and the transactions are tested for real.
 */
class Otherguise_Test_Wpdb {
	/**
	 * Table prefix.
	 *
	 * @var string
	 */
	public $prefix;

	/**
	 * Id generated by the last insert.
	 *
	 * @var int
	 */
	public $insert_id = 0;

	/**
	 * Last error message.
	 *
	 * @var string
	 */
	public $last_error = '';

	/**
	 * Queries received, in order.
	 *
	 * @var string[]
	 */
	public $queries = array();

	/**
	 * Connection, or null.
	 *
	 * @var mysqli|null
	 */
	private $mysqli;

	/**
	 * Builds the object.
	 *
	 * @param string      $prefix Table prefix.
	 * @param mysqli|null $mysqli Connection, or null to only record the queries.
	 */
	public function __construct( $prefix = 'wp_', $mysqli = null ) {
		$this->prefix = $prefix;
		$this->mysqli = $mysqli;
	}

	/**
	 * Returns the CHARACTER SET and COLLATE clause.
	 *
	 * @return string
	 */
	public function get_charset_collate() {
		return 'DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci';
	}

	/**
	 * Does nothing but keep the setting, like wpdb.
	 *
	 * @param bool $suppress Whether to suppress the errors.
	 * @return bool The previous setting.
	 */
	public function suppress_errors( $suppress = true ) {
		return false;
	}

	/**
	 * Prepares a query: `%s`, `%d` and `%i` (identifier) placeholders, with the values as arguments or as one array.
	 *
	 * @param string $query Query.
	 * @param mixed  ...$args Values.
	 * @return string
	 */
	public function prepare( $query, ...$args ) {
		if ( 1 === count( $args ) && is_array( $args[0] ) ) {
			$args = $args[0];
		}

		$index = 0;

		return preg_replace_callback(
			'/%[sdi%]/',
			function ( $match ) use ( &$index, $args ) {
				if ( '%%' === $match[0] ) {
					return '%';
				}

				$value = $args[ $index++ ];

				if ( '%d' === $match[0] ) {
					return (string) (int) $value;
				}

				if ( '%i' === $match[0] ) {
					return '`' . str_replace( '`', '``', (string) $value ) . '`';
				}

				return "'" . $this->escape( (string) $value ) . "'";
			},
			$query
		);
	}

	/**
	 * Runs a query that returns no rows.
	 *
	 * @param string $sql Query.
	 * @return int|bool Number of affected rows, or false on error.
	 */
	public function query( $sql ) {
		$this->queries[]  = $sql;
		$this->last_error = '';

		if ( null === $this->mysqli ) {
			return true;
		}

		if ( false === $this->mysqli->query( $sql ) ) {
			$this->last_error = $this->mysqli->error;

			return false;
		}

		$this->insert_id = (int) $this->mysqli->insert_id;

		return (int) $this->mysqli->affected_rows;
	}

	/**
	 * Runs a query and returns the rows as associative arrays.
	 *
	 * @param string $sql    Query.
	 * @param string $output Ignored: always associative arrays.
	 * @return array<int, array<string, string|null>>|null
	 */
	public function get_results( $sql, $output = ARRAY_A ) {
		$this->queries[]  = $sql;
		$this->last_error = '';

		if ( null === $this->mysqli ) {
			return array();
		}

		$result = $this->mysqli->query( $sql );

		if ( false === $result ) {
			$this->last_error = $this->mysqli->error;

			return null;
		}

		$rows = $result->fetch_all( MYSQLI_ASSOC );
		$result->free();

		return $rows;
	}

	/**
	 * Runs a query and returns the first column of the first row.
	 *
	 * @param string $sql Query.
	 * @return string|null
	 */
	public function get_var( $sql ) {
		$rows = $this->get_results( $sql );

		if ( empty( $rows ) ) {
			return null;
		}

		return (string) reset( $rows[0] );
	}

	/**
	 * Escapes a string for a query.
	 *
	 * @param string $value Value.
	 * @return string
	 */
	private function escape( $value ) {
		return null === $this->mysqli ? addslashes( $value ) : $this->mysqli->real_escape_string( $value );
	}
}
