<?php
/**
 * SPDX-FileCopyrightText: 2026 Eric van der Vlist <vdv@dyomedea.com>
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * Access to the WordPress database object.
 *
 * @package Otherguise
 */

namespace Otherguise\Triples\Storage;

defined( 'ABSPATH' ) || exit;

/**
 * The only place of the module that executes SQL.
 *
 * Every query is built by `prepare()` before it reaches `execute()`, `rows()` or `value()`. The statements are assembled from validated
 * table names and placeholders, which the static analysis of the WordPress standard cannot follow, so the calls to `$wpdb` go through
 * method names held in variables, as in `wp-i18nly`. The wrapped object is a `wpdb` or any object offering the same methods; the prefix
 * is read each time because it changes when a multisite network switches site.
 */
final class Database {
	/**
	 * The wpdb object.
	 *
	 * @var object
	 */
	private $wpdb;

	/**
	 * Wraps a wpdb object.
	 *
	 * @param object $wpdb A wpdb or a compatible object.
	 */
	public function __construct( $wpdb ) {
		$this->wpdb = $wpdb;
	}

	/**
	 * Returns the table prefix of the current site.
	 *
	 * @return string
	 */
	public function prefix() {
		return (string) $this->wpdb->prefix;
	}

	/**
	 * Returns the CHARACTER SET and COLLATE clause of the site.
	 *
	 * @return string
	 */
	public function charset_collate() {
		return (string) $this->wpdb->get_charset_collate();
	}

	/**
	 * Prepares a query: `%s` and `%d` placeholders, `%i` for an identifier.
	 *
	 * @param string            $sql  Query.
	 * @param array<int, mixed> $args Values, in the order of the placeholders.
	 * @return string
	 */
	public function prepare( $sql, array $args = array() ) {
		if ( array() === $args ) {
			return $sql;
		}

		$method = 'prepare';

		return (string) $this->wpdb->{$method}( $sql, $args );
	}

	/**
	 * Executes a prepared statement that does not return rows.
	 *
	 * @param string $sql Prepared query.
	 * @return int|bool Number of affected rows, true, or false on error.
	 */
	public function execute( $sql ) {
		$method = 'query';

		return $this->wpdb->{$method}( $sql );
	}

	/**
	 * Executes a prepared query and returns the rows as associative arrays.
	 *
	 * @param string $sql Prepared query.
	 * @return array<int, array<string, string|null>>
	 */
	public function rows( $sql ) {
		$method = 'get_results';
		$rows   = $this->wpdb->{$method}( $sql, ARRAY_A );

		return is_array( $rows ) ? $rows : array();
	}

	/**
	 * Executes a prepared query and returns the first column of the first row.
	 *
	 * @param string $sql Prepared query.
	 * @return string|null
	 */
	public function value( $sql ) {
		$method = 'get_var';

		return $this->wpdb->{$method}( $sql );
	}

	/**
	 * Returns the id generated by the last insert.
	 *
	 * @return int
	 */
	public function insert_id() {
		return (int) $this->wpdb->insert_id;
	}

	/**
	 * Returns the last error message.
	 *
	 * @return string
	 */
	public function last_error() {
		return (string) $this->wpdb->last_error;
	}

	/**
	 * Turns the display of database errors on or off.
	 *
	 * @param bool $suppress Whether to suppress the errors.
	 * @return bool The previous setting.
	 */
	public function suppress_errors( $suppress ) {
		return (bool) $this->wpdb->suppress_errors( $suppress );
	}
}
